///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The KillProcesses recording.
    /// </summary>
    [TestModule("81748486-ce4c-4538-8fc1-65ce753aef3c", ModuleType.Recording, 1)]
    public partial class KillProcesses : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static KillProcesses instance = new KillProcesses();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public KillProcesses()
        {
            ExcelProcess = "Excel";
            ChromeProcess = "chrome";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static KillProcesses Instance
        {
            get { return instance; }
        }

#region Variables

        string _ExcelProcess;

        /// <summary>
        /// Gets or sets the value of variable ExcelProcess.
        /// </summary>
        [TestVariable("518180b9-e78d-4fba-a74f-52718b446d24")]
        public string ExcelProcess
        {
            get { return _ExcelProcess; }
            set { _ExcelProcess = value; }
        }

        string _ChromeProcess;

        /// <summary>
        /// Gets or sets the value of variable ChromeProcess.
        /// </summary>
        [TestVariable("a3a52b27-a570-40fa-a7f7-22d39b32fbff")]
        public string ChromeProcess
        {
            get { return _ChromeProcess; }
            set { _ChromeProcess = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Ranorex.AutomationHelpers.UserCodeCollections.SystemLibrary.KillProcess(ExcelProcess);
            Delay.Milliseconds(0);
            
            Ranorex.AutomationHelpers.UserCodeCollections.SystemLibrary.KillProcess(ChromeProcess);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
