///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ReportEndtime recording.
    /// </summary>
    [TestModule("12de1f3c-a940-495e-bb7a-43b2b1b3b171", ModuleType.Recording, 1)]
    public partial class ReportEndtime : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static ReportEndtime instance = new ReportEndtime();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ReportEndtime()
        {
            EndTime = "";
            Endtimer = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ReportEndtime Instance
        {
            get { return instance; }
        }

#region Variables

        string _EndTime;

        /// <summary>
        /// Gets or sets the value of variable EndTime.
        /// </summary>
        [TestVariable("14df80e8-6f0e-43f3-aa90-5eb0cc87e37d")]
        public string EndTime
        {
            get { return _EndTime; }
            set { _EndTime = value; }
        }

        string _Endtimer;

        /// <summary>
        /// Gets or sets the value of variable Endtimer.
        /// </summary>
        [TestVariable("a50b3f70-b8fa-45bf-9712-c3193b3ae6a3")]
        public string Endtimer
        {
            get { return _Endtimer; }
            set { _Endtimer = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            EndTime = Ranorex.AutomationHelpers.UserCodeCollections.SystemLibrary.GetDateTimeAsString("");
            Delay.Milliseconds(0);
            
            Endtimer = ValueConverter.ToString(Ranorex.AutomationHelpers.UserCodeCollections.SystemLibrary.StopTimer(""));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
